import type { Metadata } from "next";
import "./globals.css";
import { Playfair_Display } from 'next/font/google'
import Navbar from "./components/layouts/Navbar";
import Footer from "./components/layouts/Footer";


const playfair = Playfair_Display({ 
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
  variable: '--font-playfair'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${playfair.className} bg-white`}>
        <Navbar/>
         {children}
        <Footer/>
      </body>
    </html>
  );
}
