import type { Metadata } from "next";
import "./globals.css";
import { Playfair_Display } from 'next/font/google'
import Navbar from "./components/layouts/Navbar";
import Footer from "./components/layouts/Footer";


const playfair = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
  fallback: ['Georgia', 'serif'], // فونت جایگزین
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={playfair.className} >
      <body>
        <Navbar/>
         {children}
        <Footer/>
      </body>
    </html>
  );
}
